import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F9FA",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F8F9FA",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#666",
  },
  header: {
    backgroundColor: "#156778",
    paddingTop: 50,
    paddingHorizontal: 20,
    paddingBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 4,
  },
  avatarContainer: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#FFF",
    justifyContent: "center",
    alignItems: "center",
  },
  userInfoRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerText: {
    flex: 1,
  },
  greeting: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#FFF",
  },
  subtitle: {
    fontSize: 13,
    color: "#FFF",
    marginTop: 2,
    textTransform: "capitalize",
    opacity: 0.9,
  },
  logoutButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  content: {
    flex: 1,
    padding: 16,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 20,
  },
  statCard: {
    width: "48%",
    backgroundColor: "#FFF",
    borderRadius: 16,
    padding: 18,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  statCardRevenue: {
    backgroundColor: "#27AE60",
  },
  statCardAppointments: {
    backgroundColor: "#F39C12",
  },
  statCardMonth: {
    backgroundColor: "#3498DB",
  },
  statCardCompleted: {
    backgroundColor: "#1ABC9C",
  },
  statIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  statValue: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#FFF",
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: "#FFF",
    opacity: 0.9,
  },
  quickActions: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 24,
  },
  actionButton: {
    flex: 1,
    backgroundColor: "#156778",
    borderRadius: 14,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
  },
  actionButtonIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  actionButtonText: {
    color: "#FFF",
    fontSize: 14,
    fontWeight: "600",
  },
  section: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
  },
  emptyState: {
    backgroundColor: "#FFF",
    borderRadius: 16,
    padding: 40,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  emptyStateText: {
    fontSize: 16,
    color: "#999",
    marginTop: 16,
    marginBottom: 20,
  },
  emptyStateButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FFF",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#156778",
  },
  emptyStateButtonText: {
    color: "#156778",
    fontSize: 14,
    fontWeight: "600",
  },
  appointmentCard: {
    backgroundColor: "#FFF",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    borderLeftWidth: 4,
    borderLeftColor: "#156778",
  },
  appointmentHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  appointmentTimeContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#156778",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
  },
  appointmentTimeText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FFF",
  },
  appointmentStatusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  appointmentStatusText: {
    fontSize: 11,
    color: "#FFF",
    fontWeight: "600",
  },
  appointmentBody: {
    gap: 10,
  },
  appointmentRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  appointmentClient: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    flex: 1,
  },
  appointmentService: {
    fontSize: 14,
    color: "#666",
    flex: 1,
  },
  appointmentPrice: {
    fontSize: 16,
    fontWeight: "700",
    color: "#4CAF50",
    flex: 1,
  },
  paymentBadgeSmall: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#F5F5F5",
    justifyContent: "center",
    alignItems: "center",
  },
  appointmentChevron: {
    position: "absolute",
    right: 16,
    top: "50%",
    marginTop: -12,
  },
  menuSection: {
    marginBottom: 24,
  },
  menuSectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  menuButton: {
    backgroundColor: "#FFF",
    borderRadius: 14,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  menuButtonIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#E8F3F5",
    justifyContent: "center",
    alignItems: "center",
  },
  menuButtonText: {
    flex: 1,
    fontSize: 16,
    color: "#333",
    fontWeight: "500",
  },
  // Estilos do Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "#FFF",
    borderRadius: 20,
    padding: 24,
    width: "100%",
    maxWidth: 400,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: "#F0F0F0",
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#2C3E50",
    flex: 1,
  },
  modalBody: {
    gap: 16,
    marginBottom: 20,
  },
  modalRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  modalRowContent: {
    flex: 1,
  },
  modalLabel: {
    fontSize: 13,
    color: "#95A5A6",
    marginBottom: 4,
    textTransform: "uppercase",
    fontWeight: "600",
  },
  modalValue: {
    fontSize: 16,
    color: "#2C3E50",
    fontWeight: "600",
  },
  modalValueHighlight: {
    fontSize: 20,
    color: "#27AE60",
    fontWeight: "700",
  },
  modalStatusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    alignSelf: "flex-start",
  },
  modalStatusText: {
    color: "#FFF",
    fontSize: 13,
    fontWeight: "700",
  },
  modalActions: {
    gap: 10,
    marginBottom: 16,
  },
  modalActionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: 14,
    borderRadius: 12,
    backgroundColor: "#F8F9FA",
    borderWidth: 2,
    borderColor: "#E8E8E8",
  },
  modalActionButtonPrimary: {
    backgroundColor: "#156778",
    borderColor: "#156778",
  },
  modalActionButtonDanger: {
    backgroundColor: "#FFF",
    borderColor: "#E74C3C",
  },
  modalActionButtonDelete: {
    backgroundColor: "#FFF",
    borderColor: "#C0392B",
  },
  modalActionButtonText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#156778",
  },
  modalActionButtonTextPrimary: {
    fontSize: 15,
    fontWeight: "700",
    color: "#FFF",
  },
  modalActionButtonTextDanger: {
    fontSize: 15,
    fontWeight: "700",
    color: "#E74C3C",
  },
  modalActionButtonTextDelete: {
    fontSize: 15,
    fontWeight: "700",
    color: "#C0392B",
  },
  modalCloseButton: {
    padding: 14,
    borderRadius: 12,
    backgroundColor: "#F8F9FA",
    alignItems: "center",
  },
  modalCloseButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#5D6D7E",
  },
  // Modal de Pagamento
  paymentSubtitle: {
    fontSize: 15,
    color: "#5D6D7E",
    marginBottom: 20,
    textAlign: "center",
  },
  paymentOptions: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
  },
  paymentOption: {
    flex: 1,
    backgroundColor: "#F8F9FA",
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    gap: 10,
    borderWidth: 2,
    borderColor: "#E8E8E8",
  },
  paymentOptionText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#2C3E50",
  },
  // Modal de Sucesso - Agendamento Concluído
  successModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  successModalContent: {
    backgroundColor: "#4CAF50",
    borderRadius: 24,
    padding: 40,
    width: "90%",
    maxWidth: 360,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 15,
  },
  successIconContainer: {
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  successTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#FFF",
    textAlign: "center",
    marginBottom: 12,
    textShadowColor: "rgba(0, 0, 0, 0.2)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  successMessage: {
    fontSize: 16,
    color: "#FFF",
    textAlign: "center",
    lineHeight: 24,
    opacity: 0.95,
  },
  successDecorative: {
    marginTop: 24,
    opacity: 0.8,
  },
});
